### ISSUE TITLE
new supplier

### ISSUE THREAD

**Issue by clbwth** [caiusCitiriga/gms#2]
when submittin a new supplier without the fk_codice_spesometro field, the server respond whith an unprocessable error "500: internal server error" instead of the usual "422: unprocessable entity". It only occurs when the field is null, not when it is empty.

**Comment by caiusCitiriga** [comment]
I think it's fixed now, check it and confirm here if the error does not occur again.

**Comment by caiusCitiriga** [comment]
Fixed with commit: fb325dee97a466bb2b6c3770056ad492be640d15
